# Default test: 5 bodies, 20 steps, no missile
address = "1"

bodies = [
  ["126000", "32000", "22000", "12000", "8000"],
  ["226000", "42000", "21000", "11000", "7000"],
  ["0", "0", "20000", "20000", "0"],
  ["0", "0", "20000", "20000", "0"],
  ["0", "0", "20000", "20000", "0"]
]

inflight_missile = ["0", "1000000", "0", "0", "0"]

missiles = [
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"],
  ["0", "0", "0"]
]
