// Emits JavaScript (ESM, BigInt arithmetic) from a parsed Circom AST.
//
// Mapping strategy:
//
//   circom function f(a, b) { ... }      →  export function f(a, b) { ... }
//   circom template T(p) { ... }         →  export function T(p) { return function compute(inputs) { ... return { outputs } } }
//
//   signal input x        → an entry in `inputs`, referred to as `inputs.x`
//   signal output y       → a local `let y`, returned in the outputs object
//   signal z              → a local `let z`
//   signal a <== expr     → `let a = expr` (first occurrence) or `a = expr`
//   var x = expr          → `let x = expr`
//   x <== expr            → `x = expr`
//   x <-- expr            → `x = expr` (witness assignment — same thing in JS)
//   x === y               → `if (x !== y) throw ...` in checked mode, else skipped
//
// Components: lazy proxy helper (runtime/component.js). On component decl,
// we emit a LazyComponent wrapper. On `comp.foo = x` or `comp.foo[i] = x`,
// we emit the plain property write. On `comp.out`, we emit the property read
// (which triggers the deferred compute in the runtime).
//
// Number literals: emitted as BigInt literals (append 'n').

// Known I/O signatures for circomlib templates handled by the runtime.
// Matches runtime/circomlib.js.
const BUILTIN_IO = {
  IsZero: { inputs: ['in'], outputs: ['out'] },
  IsEqual: { inputs: ['in'], outputs: ['out'] },
  LessThan: { inputs: ['in'], outputs: ['out'] },
  LessEqThan: { inputs: ['in'], outputs: ['out'] },
  GreaterThan: { inputs: ['in'], outputs: ['out'] },
  GreaterEqThan: { inputs: ['in'], outputs: ['out'] },
  AND: { inputs: ['a', 'b'], outputs: ['out'] },
  OR: { inputs: ['a', 'b'], outputs: ['out'] },
  XOR: { inputs: ['a', 'b'], outputs: ['out'] },
  NOT: { inputs: ['in'], outputs: ['out'] },
  NAND: { inputs: ['a', 'b'], outputs: ['out'] },
  NOR: { inputs: ['a', 'b'], outputs: ['out'] },
  MultiAND: { inputs: ['in'], outputs: ['out'] },
  Mux1: { inputs: ['c', 's'], outputs: ['out'] },
  MultiMux1: { inputs: ['c', 's'], outputs: ['out'] },
  Num2Bits: { inputs: ['in'], outputs: ['out'] },
  Num2Bits_strict: { inputs: ['in'], outputs: ['out'] },
  Bits2Num: { inputs: ['in'], outputs: ['out'] },
  Bits2Num_strict: { inputs: ['in'], outputs: ['out'] },
  AliasCheck: { inputs: ['in'], outputs: [] },
  CompConstant: { inputs: ['in'], outputs: ['out'] },
}

// JS reserved words that might appear as circom identifiers.
// Identifiers matching these are prefixed with `_` when emitted as bare
// variable references. Property access (x.in) is fine unescaped.
const JS_RESERVED = new Set([
  'in',
  'of',
  'class',
  'new',
  'delete',
  'this',
  'super',
  'null',
  'case',
  'switch',
  'default',
  'break',
  'continue',
  'import',
  'export',
  'yield',
  'async',
  'await',
  'try',
  'catch',
  'finally',
  'throw',
  'typeof',
  'instanceof',
  'void',
  'let',
  'const',
  'enum',
  'extends',
])

function escId(name) {
  return JS_RESERVED.has(name) ? '_' + name : name
}

export function emit(ast, opts = {}) {
  const checked = opts.checked === true
  const runtimePath = opts.runtimePath ?? './runtime/circomlib.js'
  // Build template registry from this file (extend for multi-file later).
  const registry = { ...BUILTIN_IO }
  for (const tpl of ast.templates) {
    registry[tpl.name] = collectSignals(tpl.body)
  }
  if (opts.extraTemplates) {
    for (const [name, sig] of Object.entries(opts.extraTemplates)) {
      registry[name] = sig
    }
  }
  const e = new Emitter(checked, runtimePath, registry)
  return e.emitFile(ast)
}

class Emitter {
  constructor(checked, runtimePath, registry) {
    this.checked = checked
    this.runtimePath = runtimePath
    this.registry = registry
    this.out = []
    this.indent = 0
  }

  w(s) {
    if (s === '' || s === null || s === undefined) {
      this.out.push('')
      return
    }
    const pad = '  '.repeat(this.indent)
    this.out.push(pad + s)
  }

  // Emit a full file.
  emitFile(ast) {
    this.out = []
    // Header
    this.w(`// AUTO-GENERATED by circom2js. Do not edit.`)
    this.w(`// Source: ${ast.filename}`)
    this.w('')
    // Import circomlib runtime primitives. The transpiler conservatively
    // imports everything and lets the JS tree-shaker drop unused bits.
    this.w(`import {`)
    this.indent++
    const runtimeExports = [
      'LazyComponent',
      'IsZero',
      'IsEqual',
      'LessThan',
      'LessEqThan',
      'GreaterThan',
      'GreaterEqThan',
      'AND',
      'OR',
      'XOR',
      'NOT',
      'NAND',
      'NOR',
      'MultiAND',
      'Mux1',
      'MultiMux1',
      'Num2Bits',
      'Num2Bits_strict',
      'Bits2Num',
      'Bits2Num_strict',
      'AliasCheck',
      'CompConstant',
    ]
    for (const sym of runtimeExports) this.w(sym + ',')
    this.indent--
    this.w(`} from '${this.runtimePath}'`)
    this.w('')

    // Functions first (templates may reference them).
    for (const fn of ast.functions) this.emitFunction(fn)
    for (const tpl of ast.templates) this.emitTemplate(tpl)

    return this.out.join('\n') + '\n'
  }

  // ---- functions ----

  emitFunction(fn) {
    const params = fn.params.map(escId).join(', ')
    this.w(`export function ${fn.name}(${params}) {`)
    this.indent++
    this.emitBody(fn.body, { inFunction: true })
    this.indent--
    this.w(`}`)
    this.w('')
  }

  // ---- templates ----

  emitTemplate(tpl) {
    // Pre-scan body for signal inputs and outputs.
    const { inputs, outputs } = collectSignals(tpl.body)

    // Pre-scan body for component declarations so we know input/output fields
    // per component (needed only for documentation; runtime uses LazyComponent
    // + the field sets declared by the called template at runtime time).

    const params = tpl.params.map(escId).join(', ')
    this.w(`export function ${tpl.name}(${params}) {`)
    this.indent++
    this.w(`return function compute(inputs) {`)
    this.indent++
    // Bind each declared input signal to a local name so the body can use it
    // by its bare name (matching the circom source).
    for (const inp of inputs) {
      this.w(`const ${escId(inp)} = inputs.${inp}`)
    }
    // Declare outputs as let (so the body can assign them).
    for (const out of outputs) {
      this.w(`let ${escId(out)}`)
    }
    // Body
    this.emitBody(tpl.body, { inTemplate: true, outputs: new Set(outputs) })
    // Return outputs object — map from circom names (keys) to JS names (values).
    if (outputs.length > 0) {
      const parts = outputs.map((o) =>
        o === escId(o) ? o : `${o}: ${escId(o)}`
      )
      this.w(`return { ${parts.join(', ')} }`)
    } else {
      this.w(`return {}`)
    }
    this.indent--
    this.w(`}`)
    this.indent--
    this.w(`}`)
    this.w('')
  }

  // ---- body / statements ----

  emitBody(block, ctx) {
    for (const stmt of block.body) this.emitStmt(stmt, ctx)
  }

  emitStmt(s, ctx) {
    switch (s.type) {
      case 'Block':
        this.w('{')
        this.indent++
        this.emitBody(s, ctx)
        this.indent--
        this.w('}')
        break
      case 'SignalDecl':
        this.emitSignalDecl(s, ctx)
        break
      case 'VarDecl':
        this.emitVarDecl(s, ctx)
        break
      case 'ComponentDecl':
        this.emitComponentDecl(s, ctx)
        break
      case 'For': {
        const init = s.init
        let initStr
        if (init.type === 'VarDecl') {
          // Inline: `let x = 0`
          initStr = varDeclInline(init, this)
        } else if (init.type === 'Assign') {
          initStr = assignInline(init, this)
        } else {
          initStr = this.emitExpr(init.expr)
        }
        const cond = this.emitExpr(s.cond)
        const update = updateInline(s.update, this)
        this.w(`for (${initStr}; ${cond}; ${update}) {`)
        this.indent++
        // For body: single stmt (often a Block)
        if (s.body.type === 'Block') this.emitBody(s.body, ctx)
        else this.emitStmt(s.body, ctx)
        this.indent--
        this.w(`}`)
        break
      }
      case 'While':
        this.w(`while (${this.emitExpr(s.cond)}) {`)
        this.indent++
        if (s.body.type === 'Block') this.emitBody(s.body, ctx)
        else this.emitStmt(s.body, ctx)
        this.indent--
        this.w(`}`)
        break
      case 'If':
        this.w(`if (${this.emitExpr(s.cond)}) {`)
        this.indent++
        if (s.cons.type === 'Block') this.emitBody(s.cons, ctx)
        else this.emitStmt(s.cons, ctx)
        this.indent--
        if (s.alt) {
          if (s.alt.type === 'If') {
            // else if — avoid nested braces blow-up
            this.w(`} else if (${this.emitExpr(s.alt.cond)}) {`)
            this.indent++
            if (s.alt.cons.type === 'Block') this.emitBody(s.alt.cons, ctx)
            else this.emitStmt(s.alt.cons, ctx)
            this.indent--
            if (s.alt.alt) {
              this.w(`} else {`)
              this.indent++
              if (s.alt.alt.type === 'Block') this.emitBody(s.alt.alt, ctx)
              else this.emitStmt(s.alt.alt, ctx)
              this.indent--
            }
            this.w(`}`)
          } else {
            this.w(`} else {`)
            this.indent++
            if (s.alt.type === 'Block') this.emitBody(s.alt, ctx)
            else this.emitStmt(s.alt, ctx)
            this.indent--
            this.w(`}`)
          }
        } else {
          this.w(`}`)
        }
        break
      case 'Return':
        if (s.value === null) this.w(`return`)
        else this.w(`return ${this.emitExpr(s.value)}`)
        break
      case 'ExprStmt':
        this.w(`${this.emitExpr(s.expr)}`)
        break
      case 'Update':
        this.w(`${this.emitExpr(s.arg)} ${s.op === '++' ? '+=' : '-='} 1n`)
        break
      case 'Assign':
        this.emitAssign(s, ctx)
        break
      default:
        throw new Error(`emitStmt: unhandled ${s.type}`)
    }
  }

  emitSignalDecl(s, ctx) {
    // `signal input x` — no local decl; inputs.x is already bound.
    // `signal output y` — output already declared at template top.
    // `signal z` or `signal z <== expr` — declare a local.
    for (const d of s.decls) {
      if (s.direction === 'input') {
        // If input has array dims declared on the template signal (e.g. in[n]),
        // it's still just a named field on the inputs object. The `const ${d.name} = inputs.${d.name}` line
        // at the top of compute() already bound it, so nothing to emit here.
        continue
      }
      if (s.direction === 'output') {
        // Already declared as `let` at the top of compute().
        if (d.init) {
          // Output declared with inline assignment: `signal output foo <== ...`
          this.w(`${d.name} = ${this.emitExpr(d.init.rhs)}`)
        }
        continue
      }
      // Intermediate signal
      if (d.dims.length > 0) {
        // Declare an array slot: `let name = new Array(dim)`
        this.w(`let ${d.name} = ${arrayOf(d.dims, this)}`)
      } else if (d.init) {
        this.w(`let ${d.name} = ${this.emitExpr(d.init.rhs)}`)
      } else {
        this.w(`let ${d.name}`)
      }
    }
  }

  emitVarDecl(s, ctx) {
    for (const d of s.decls) {
      if (d.dims.length > 0) {
        if (d.init) {
          this.w(`let ${d.name} = ${this.emitExpr(d.init)}`)
        } else {
          this.w(`let ${d.name} = ${arrayOf(d.dims, this)}`)
        }
      } else {
        this.w(
          d.init ? `let ${d.name} = ${this.emitExpr(d.init)}` : `let ${d.name}`
        )
      }
    }
  }

  emitComponentDecl(s, ctx) {
    if (s.dims.length > 0) {
      // component foo[N]; declare slot array.
      this.w(`let ${s.name} = new Array(${this.emitExpr(s.dims[0])})`)
      for (let i = 1; i < s.dims.length; i++) {
        // multi-dim component arrays: caller fills them in
      }
      if (s.call) {
        // e.g. `component foo[n] = Foo(...)` — not commonly used; we don't
        // auto-fill, the user's code will do `foo[i] = Foo(...)`.
        this.w(
          `// Note: component array with inline init is uncommon; ${s.name} left as empty slots`
        )
      }
      return
    }
    if (!s.call) {
      this.w(`let ${s.name}`)
      return
    }
    const callee = s.call.callee.name
    const args = s.call.args.map((a) => this.emitExpr(a)).join(', ')
    const sig = this.registry[callee]
    if (!sig) {
      throw new Error(
        `component ${s.name}: unknown template '${callee}' (not parsed and not a builtin). ` +
          `Pass it via opts.extraTemplates or ensure the defining file is transpiled together.`
      )
    }
    const inputList = sig.inputs.map((x) => `'${x}'`).join(', ')
    const outputList = sig.outputs.map((x) => `'${x}'`).join(', ')
    this.w(
      `let ${s.name} = LazyComponent(() => ${callee}(${args}), [${inputList}], [${outputList}])`
    )
  }

  emitAssign(s, ctx) {
    const op = s.op
    if (op === '===') {
      // Constraint check. In checked mode, assert equality.
      if (this.checked) {
        this.w(
          `if ((${this.emitExpr(s.lhs)}) !== (${this.emitExpr(s.rhs)})) throw new Error('constraint failed')`
        )
      } else {
        // Silent in witness-gen mode.
        this.w(
          `// constraint: ${this.emitExpr(s.lhs)} === ${this.emitExpr(s.rhs)}`
        )
      }
      return
    }
    // Signal/var assignment: plain JS assignment.
    const lhs = this.emitExpr(s.lhs)
    const rhs = this.emitExpr(s.rhs)
    const jsOp = op === '<==' || op === '<--' || op === '=' ? '=' : op
    this.w(`${lhs} ${jsOp} ${rhs}`)
  }

  // ---- expressions ----

  emitExpr(e) {
    switch (e.type) {
      case 'Number':
        // BigInt literal
        return e.value + 'n'
      case 'Ident':
        return escId(e.name)
      case 'Unary':
        return `(${e.op}${this.emitExpr(e.arg)})`
      case 'Binary': {
        const l = this.emitExpr(e.lhs)
        const r = this.emitExpr(e.rhs)
        switch (e.op) {
          case '**':
            return `(${l} ** ${r})`
          case '/':
          case '\\':
            // BigInt / is already integer division.
            return `(${l} / ${r})`
          case '==':
          case '!=':
            // BigInt equality; use === for identity on the same-typed operands
            return `(${l} ${e.op === '==' ? '===' : '!=='} ${r})`
          case '&&':
          case '||':
            // circom treats non-zero as true; BigInt 0n is falsy in JS too.
            return `(${l} ${e.op} ${r})`
          default:
            return `(${l} ${e.op} ${r})`
        }
      }
      case 'Ternary':
        return `(${this.emitExpr(e.cond)} ? ${this.emitExpr(e.cons)} : ${this.emitExpr(e.alt)})`
      case 'Member':
        // Property access: field names can be reserved words in JS.
        return `${this.emitExpr(e.object)}.${e.field}`
        // Note: do NOT escape field names — `x.in` and `x.class` are fine.
      case 'Index':
        return `${this.emitExpr(e.object)}[${this.emitExpr(e.index)}]`
      case 'Call': {
        const callee = this.emitExpr(e.callee)
        const args = e.args.map((a) => this.emitExpr(a)).join(', ')
        return `${callee}(${args})`
      }
      case 'Array':
        return `[${e.elements.map((x) => this.emitExpr(x)).join(', ')}]`
      default:
        throw new Error(`emitExpr: unhandled ${e.type}`)
    }
  }
}

// Helpers --------------------------------------------------------------

function collectSignals(block) {
  const inputs = []
  const outputs = []
  function walk(node) {
    if (!node) return
    if (node.type === 'SignalDecl') {
      for (const d of node.decls) {
        if (node.direction === 'input') inputs.push(d.name)
        else if (node.direction === 'output') outputs.push(d.name)
      }
      return
    }
    // Recurse into statement containers (we only need top-level decls,
    // but circuits sometimes declare outputs deeper — walk everything).
    for (const k of Object.keys(node)) {
      const v = node[k]
      if (v && typeof v === 'object') {
        if (Array.isArray(v)) v.forEach(walk)
        else if (v.type) walk(v)
      }
    }
  }
  walk(block)
  return { inputs, outputs }
}

function arrayOf(dims, emitter) {
  // Produce `new Array(dim0).fill(0n)` or nested for 2D. Falls back to a
  // generic builder for >2D.
  if (dims.length === 1) return `new Array(Number(${emitter.emitExpr(dims[0])}))`
  if (dims.length === 2) {
    const d0 = emitter.emitExpr(dims[0])
    const d1 = emitter.emitExpr(dims[1])
    return `Array.from({length: Number(${d0})}, () => new Array(Number(${d1})))`
  }
  const ds = dims.map((d) => `Number(${emitter.emitExpr(d)})`).join(', ')
  return `__nestedArray__([${ds}])`
}

function varDeclInline(v, emitter) {
  // let x = init, y = init2
  const parts = v.decls.map((d) => {
    if (d.dims.length > 0) return `${d.name} = ${arrayOf(d.dims, emitter)}`
    if (d.init) return `${d.name} = ${emitter.emitExpr(d.init)}`
    return d.name
  })
  return `let ${parts.join(', ')}`
}

function assignInline(a, emitter) {
  const op = a.op
  const lhs = emitter.emitExpr(a.lhs)
  const rhs = emitter.emitExpr(a.rhs)
  const jsOp = op === '<==' || op === '<--' ? '=' : op
  return `${lhs} ${jsOp} ${rhs}`
}

function updateInline(u, emitter) {
  if (u.type === 'Update') {
    return `${emitter.emitExpr(u.arg)} ${u.op === '++' ? '+=' : '-='} 1n`
  }
  if (u.type === 'Assign') {
    return assignInline(u, emitter)
  }
  if (u.type === 'ExprStmt') {
    return emitter.emitExpr(u.expr)
  }
  throw new Error(`updateInline: unhandled ${u.type}`)
}
