// AUTO-GENERATED by circom2js. Do not edit.
// Source: approxMath.circom

import {
  LazyComponent,
  IsZero,
  IsEqual,
  LessThan,
  LessEqThan,
  GreaterThan,
  GreaterEqThan,
  AND,
  OR,
  XOR,
  NOT,
  NAND,
  NOR,
  MultiAND,
  Mux1,
  MultiMux1,
  Num2Bits,
  Num2Bits_strict,
  Bits2Num,
  Bits2Num_strict,
  AliasCheck,
  CompConstant,
} from '../runtime/circomlib.js'

export function approxSqrt(n) {
  if ((n === 0n)) {
    return [0n, 0n, 0n]
  }
  let lo = 0n
  let hi = (n >> 1n)
  let mid
  let midSquared
  while ((lo <= hi)) {
    mid = ((lo + hi) >> 1n)
    midSquared = (mid * mid)
    if ((midSquared === n)) {
      return [lo, mid, hi]
    } else if ((midSquared < n)) {
      lo = (mid + 1n)
    } else {
      hi = (mid - 1n)
    }
  }
  return [lo, mid, hi]
}

export function approxDiv(dividend, divisor) {
  if ((dividend === 0n)) {
    return 0n
  }
  let lo
  let hi
  let mid
  let testProduct
  lo = 0n
  hi = dividend
  while ((lo < hi)) {
    mid = (((hi + lo) + 1n) >> 1n)
    testProduct = (mid * divisor)
    if ((testProduct > dividend)) {
      hi = (mid - 1n)
    } else {
      lo = mid
    }
  }
  return lo
}

export function Div() {
  return function compute(inputs) {
    const dividend = inputs.dividend
    const divisor = inputs.divisor
    let quotient
    quotient = approxDiv(dividend, divisor)
    let approxNumerator1 = (quotient * divisor)
    let diff = (dividend - quotient)
    let lessThan = LazyComponent(() => LessEqThan(64n), ['in'], ['out'])
    lessThan.in[0n] = diff
    lessThan.in[1n] = dividend
    let isZero = LazyComponent(() => IsZero(), ['in'], ['out'])
    isZero.in = dividend
    let or = LazyComponent(() => OR(), ['a', 'b'], ['out'])
    or.a = isZero.out
    or.b = lessThan.out
    // constraint: or.out === 1n
    return { quotient }
  }
}

export function Sqrt(unboundDistanceSquaredMax) {
  return function compute(inputs) {
    const squaredValue = inputs.squaredValue
    let root
    let approxSqrtResults = new Array(Number(3n))
    approxSqrtResults = approxSqrt(squaredValue)
    root = approxSqrtResults[1n]
    let distanceResults = new Array(Number(3n))
    distanceResults = approxSqrt(unboundDistanceSquaredMax)
    let distanceMax = distanceResults[1n]
    let distanceMaxBits = maxBits(distanceMax)
    let isPerfect = LazyComponent(() => IsZero(), ['in'], ['out'])
    isPerfect.in = ((root ** 2n) - squaredValue)
    let isZeroDiff2 = LazyComponent(() => IsZero(), ['in'], ['out'])
    isZeroDiff2.in = (approxSqrtResults[0n] - approxSqrtResults[1n])
    let isZeroDiff3 = LazyComponent(() => IsZero(), ['in'], ['out'])
    isZeroDiff3.in = (approxSqrtResults[2n] - approxSqrtResults[1n])
    let firstCondition = LazyComponent(() => XOR(), ['a', 'b'], ['out'])
    firstCondition.a = isZeroDiff2.out
    firstCondition.b = isZeroDiff3.out
    let secondCondition = LazyComponent(() => OR(), ['a', 'b'], ['out'])
    secondCondition.a = firstCondition.out
    secondCondition.b = isPerfect.out
    // constraint: secondCondition.out === 1n
    let diffMux = LazyComponent(() => Mux1(), ['c', 's'], ['out'])
    diffMux.c[0n] = ((approxSqrtResults[1n] ** 2n) - squaredValue)
    diffMux.c[1n] = (squaredValue - (approxSqrtResults[1n] ** 2n))
    diffMux.s = isZeroDiff3.out
    let imperfectDiff = diffMux.out
    let diffMux2 = LazyComponent(() => Mux1(), ['c', 's'], ['out'])
    diffMux2.c[0n] = imperfectDiff
    diffMux2.c[1n] = 0n
    diffMux2.s = isPerfect.out
    let diff = diffMux2.out
    let distanceMaxDoubleMax = (distanceMax * 2n)
    let distanceMaxSquaredMaxBits = maxBits(distanceMaxDoubleMax)
    let lessThan2 = LazyComponent(() => LessEqThan(distanceMaxSquaredMaxBits), ['in'], ['out'])
    lessThan2.in[0n] = diff
    lessThan2.in[1n] = (root * 2n)
    // constraint: lessThan2.out === 1n
    return { root }
  }
}

export function AcceptableMarginOfError(n) {
  return function compute(inputs) {
    const expected = inputs.expected
    const actual = inputs.actual
    const marginOfError = inputs.marginOfError
    let out
    let absoluteValueSubtraction = LazyComponent(() => AbsoluteValueSubtraction(n), ['in'], ['out'])
    absoluteValueSubtraction.in[0n] = expected
    absoluteValueSubtraction.in[1n] = actual
    let lessThan2 = LazyComponent(() => LessEqThan(n), ['in'], ['out'])
    lessThan2.in[0n] = absoluteValueSubtraction.out
    lessThan2.in[1n] = marginOfError
    out = lessThan2.out
    return { out }
  }
}

export function AbsoluteValueSubtraction(n) {
  return function compute(inputs) {
    const _in = inputs.in
    let out
    let lessThan = LazyComponent(() => LessThan(n), ['in'], ['out'])
    lessThan.in[0n] = _in[0n]
    lessThan.in[1n] = _in[1n]
    let lessThanResult = lessThan.out
    let myMux = LazyComponent(() => Mux1(), ['c', 's'], ['out'])
    myMux.c[0n] = _in[0n]
    myMux.c[1n] = _in[1n]
    myMux.s = lessThanResult
    let greaterValue = myMux.out
    let isZero = LazyComponent(() => IsZero(), ['in'], ['out'])
    isZero.in = (greaterValue - _in[0n])
    let myMux2 = LazyComponent(() => Mux1(), ['c', 's'], ['out'])
    myMux2.c[0n] = _in[0n]
    myMux2.c[1n] = _in[1n]
    myMux2.s = isZero.out
    let lesserValue = myMux2.out
    out = (greaterValue - lesserValue)
    return { out }
  }
}

