// AUTO-GENERATED by circom2js. Do not edit.
// Source: helpers.circom

import {
  LazyComponent,
  IsZero,
  IsEqual,
  LessThan,
  LessEqThan,
  GreaterThan,
  GreaterEqThan,
  AND,
  OR,
  XOR,
  NOT,
  NAND,
  NOR,
  MultiAND,
  Mux1,
  MultiMux1,
  Num2Bits,
  Num2Bits_strict,
  Bits2Num,
  Bits2Num_strict,
  AliasCheck,
  CompConstant,
} from '../runtime/circomlib.js'

export function getX(body) {
  return body[0n]
}

export function getY(body) {
  return body[1n]
}

export function getVx(body) {
  return body[2n]
}

export function getVy(body) {
  return body[3n]
}

export function getMass(body) {
  return body[4n]
}

export function maxBits(n) {
  let i = 0n
  while ((n > 0n)) {
    i += 1n
    n = (n >> 1n)
  }
  return i
}

export function getBiggest(options, len) {
  let biggest = 0n
  for (let i = 0n; (i < len); i += 1n) {
    if ((options[i] > biggest)) {
      biggest = options[i]
    }
  }
  return biggest
}

